### ISSUE TITLE
Missing wiki

### ISSUE THREAD

**Issue by itsvrl** [CrispyPin/ovr-utils#1]
Should create a wiki page. Just make the base line, I can then fork it and do pull requests on the wiki to help with documentation if you want.

Things like

- Install prosess
- Usage in diffrent OS
- Start up steps
etc...

**Comment by CrispyPin** [comment]
I feel like the basic stuff like installation and startup should be in the readme, while the wiki can be used for things like how it works and how to create new overlay types

**Comment by itsvrl** [comment]
> I feel like the basic stuff like installation and startup should be in the readme, while the wiki can be used for things like how it works and how to create new overlay types

I agree, the readme should have the raw basics 👍

But for more I guess having a wiki would be really nice
