### ISSUE TITLE
Fix your shit

### ISSUE THREAD

**Issue by gtgt12** [CrispyPin/ovr-utils#2]
BUG #1 / infinity  
![Elp](https://user-images.githubusercontent.com/85445122/120927025-aa2cc700-c6df-11eb-9979-1d728fffa478.PNG)

**Comment by gtgt12** [comment]
+ low FPS in VRC

**Comment by itsvrl** [comment]
Looks like a you problem, also your bug report is trash because it does not tell anything. HOW are ANYONE understand your issue when you can't even explain what your issue is...

**Comment by CrispyPin** [comment]
@vrlnx the bug is that the menu buttons are elongated, I don't know what caused it though. I cleaned up the ui hierachy a bit so maybe it will be fixed in the next update
