### ISSUE TITLE
Build instructions and contribution guide

### ISSUE THREAD

**Issue by nicholas-sly** [CrispyPin/ovr-utils#6]
I've forked your repository in order to try adding some new simple overlays.  I'm new to the godot and openvr ecosystem, but am running a Valve Index on PopOS and would like to help out with small things on this repository to improve the project.  I've put together the tcsm and gd files (based off of the time and battery files), but I don't know how to build it in order to test.

I can understand if you don't have the time, but if you do, I'd be happy to try and knock out some of the simpler issues on your project board.

Thanks for your great work on this project, btw.  Was hoping to find any kind of overlay that works on Linux.

**Comment by CrispyPin** [comment]
Thanks for your interest in the project!

You can build the project from Godot by clicking Project -> Export then "Export Project" under the right platform. You will need to get the export templates installed but the editor guides you through that. For testing purposes it should™ just work to run it in the editor, which is very helpful for debugging, and you don't need the export templates for it.
