### ISSUE TITLE
How to write an OpenVR overlay.

### ISSUE THREAD

**Issue by TitansWhale** [CrispyPin/ovr-utils#7]
Thank you for creating "ovr-utils". I am currently working on a similar software using "ovr-utils" as a reference.
As a Godot beginner, this project is too complex for me, and I'm not quite clear about its workings. Moreover, I am unable to run this project in Godot 3.5.
I tried to follow the official example at [Using-OpenVR-overlays](https://github.com/GodotVR/godot_openvr/wiki/Using-OpenVR-overlays)to write the overlay but I haven't succeeded. I am unsure about what is causing the issue.
my example as follows:
[godot_openvr_overlay_test](https://github.com/TitansWhale/godot_openvr_overlay_test)

**Comment by CrispyPin** [comment]
This project is likely using Godot 3.4, it was quite a while since I worked on it.

I'll probably have a look at your project later this week

**Comment by TitansWhale** [comment]
> This project is likely using Godot 3.4, it was quite a while since I worked on it.
> 
> I'll probably have a look at your project later this week


I reexamined your project, and I found that it functions correctly. However, there were some notifications that initially made me think it wasn't working properly. It was my oversight not to provide the error messages directly from the beginning.now it could work. but I don't know how to run the [Using-OpenVR-overlays](https://github.com/GodotVR/godot_openvr/wiki/Using-OpenVR-overlays).
![image](https://github.com/CrispyPin/ovr-utils/assets/26743177/552300de-aff4-45ee-85ad-61e6163610ff)

**Comment by CrispyPin** [comment]
You forgot to set the viewport "Update mode" to "Always", it's mentioned in the guide but very easy to miss. Without that it stays transparent even though the overlay is technically rendering.

**Comment by CrispyPin** [comment]
The errors about battery status are probably there because SteamVR doesn't have the information it's requesting, I think it only works with SteamVR hardware (Vive, Index). It should handle that error instead of trying over and over, but I don't think I'll work on OVR Utils again.

**Comment by TitansWhale** [comment]
> You forgot to set the viewport "Update mode" to "Always", it's mentioned in the guide but very easy to miss. Without that it stays transparent even though the overlay is technically rendering.

thank you
